### PR TITLE
Upload screenshot to GitHub CDN

### PR DESCRIPTION
**Pull request by vinkla**
This pull request move the screenshot to GitHub's CDN which means we don't have to commit the image to the repository. The image has been uploaded simply by drag-n-drop into an GitHub issue. We don't want the force the user to download the image which was achieved in #18. Though, this means the screenshot wont appear within the Atom settings. This pull request fixes that.

### CODE REVIEW

**Comment by appelgriebsch** [comment]
How did you upload it there - in case I'll have to update it later...

**Comment by robertrossmann** [comment]
You just drop the file into any Github issue textbox area and copy the URL out of it. 💯

**Comment by vinkla** [comment]
@appelgriebsch I put together a guide a while back. [You can find it here.](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d)

**Pull request merged**
