### PR TITLE
Change the style of the datatip to match other Atom popovers

### PR DESCRIPTION
**Pull request by illright**
No idea why, but it keeps rejecting my pushes to branches, so I had to fork.

The datatip looks a bit rough with its shadow and sharp corners, the Autocomplete popover looks much cleaner, imho. This will add the necessary classes to the datatip to make it look like Autocomplete. This can also potentially help with the theming, not sure.

<details>
  <summary>Before:</summary>
  </img>
</details>

<details>
  <summary>After:</summary>
  </img>
</details>

This will also update the lockfile.

### CODE REVIEW

**Comment by aminya** [comment]
Where is this class defined? Does this mean that autocomplete should be activated?

**Comment by illright** [comment]
@aminya [Atom Core](https://github.com/atom/atom/blob/976cb9ef3a611163052f9d31c6c3685dc1e6c5b4/static/atom-ui/styles/select-list.less#L45), supposedly, and overriden in [Atom Core themes](https://github.com/atom/atom/blob/976cb9ef3a611163052f9d31c6c3685dc1e6c5b4/packages/one-light-ui/styles/lists.less#L108).

Also it seems like the CI is failing due to this being a fork

**Comment by aminya** [comment]
> Also it seems like the CI is failing due to this being a fork

You should follow the semantic release commit style. Add `fix: ` before the commit message

**Review by aminya — APPROVED** [review]
Thanks!

**Pull request merged**
